import type { MunicipalityPresentation } from '@/lib/presentation-contract';

const monthNames = ['janeiro', 'fevereiro', 'março', 'abril', 'maio', 'junho', 'julho', 'agosto', 'setembro', 'outubro', 'novembro', 'dezembro'];
export function TypesAndMonths({ disasters }: { disasters: MunicipalityPresentation['disasters'] }) {
  const total = disasters.history.rain_related_event_count;
  if (!total) return <section className="grid gap-5 md:grid-cols-2"><Absence title="Que tipo de evento aparece mais?" /><Absence title="Em que época aparecem mais registros?" /></section>;
  const top = disasters.types[0];
  const topMonths = disasters.months.filter((item) => item.rain_related_event_count > 0).sort((a,b) => b.rain_related_event_count-a.rain_related_event_count).slice(0,3);
  const monthCount = topMonths.reduce((sum, item) => sum + item.rain_related_event_count, 0);
  return <section className="grid gap-5 md:grid-cols-2"><article className="elevated-card rounded-2xl bg-card p-5 shadow-[0_12px_45px_rgb(21_42_57/8%)]"><h2 className="font-heading text-2xl font-semibold">Que tipo de evento aparece mais?</h2><div className="mt-5 space-y-3">{disasters.types.map((type) => <div key={type.atlas_type_id}><div className="flex justify-between gap-2 text-sm"><span>{type.type_name}</span><strong>{type.event_count} · {type.event_pct.toFixed(0)}%</strong></div><div className="mt-1 h-2 rounded bg-muted"><div className="h-2 rounded bg-rain-strong" style={{width:`${type.event_pct}%`}} /></div></div>)}</div><p className="mt-5 text-sm text-muted-foreground">{top.type_name} representa {top.event_pct.toFixed(0)}% dos registros relacionados à chuva encontrados para o município.</p></article><article className="elevated-card rounded-2xl bg-card p-5 shadow-[0_12px_45px_rgb(21_42_57/8%)]"><h2 className="font-heading text-2xl font-semibold">Em que época aparecem mais registros?</h2><div className="mt-5 grid grid-cols-6 gap-2">{disasters.months.map((item, index) => <div className="text-center text-xs" key={item.month}><div className="h-20 flex items-end rounded bg-muted"><div className="w-full bg-primary" style={{height:`${(item.rain_related_event_count / Math.max(...disasters.months.map(x=>x.rain_related_event_count),1))*100}%`}} /></div><strong>{index + 1}</strong><span className="block">{item.rain_related_event_count}</span></div>)}</div><p className="mt-5 text-sm text-muted-foreground">Os meses de {topMonths.map(item => monthNames[item.month - 1]).join(', ')} concentram {(monthCount / total * 100).toFixed(0)}% dos registros da série.</p></article></section>;
}
function Absence({title}:{title:string}) { return <article className="rounded-2xl border border-dashed border-border p-5"><h2 className="font-heading text-2xl font-semibold">{title}</h2><p className="mt-3 text-sm text-muted-foreground">Não há registros relacionados à chuva no recorte publicado; por isso não há gráfico zerado.</p></article>; }
